[build]

Comando de construcci칩n para React

command = "npm run build"

Directorio donde se publican los archivos est치ticos (el resultado de 'npm run build')

publish = "build"

[functions]

Directorio donde se encuentran todas las funciones serverless (Netlify Functions)

directory = "netlify/functions"

Tiempo de espera de 10 segundos para la funci칩n

timeout = 10

[[redirects]]

Regla de redirecci칩n para que todas las rutas internas sean manejadas por React (history API)

from = "/*"
to = "/index.html"
status = 200